apiVersion: v1
# 定义一个k8s的volume
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  storageClassName: mysql-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/webook"