apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-claim
  labels:
    app: webook-mysql-claim
spec:
  # 随便取
  storageClassName: mysql-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # 1 GB
      storage: 1Gi